// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnubk7dlL9b4uO9WQ1NyNsslDn9VhfPI',
    appId: '1:90632323398:web:cb283f6b081431e206a547',
    messagingSenderId: '90632323398',
    projectId: 'scorewizard-3d1e9',
    authDomain: 'scorewizard-3d1e9.firebaseapp.com',
    storageBucket: 'scorewizard-3d1e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAas8NiRgoAKZ2rOY_0TXGfzMT27LiSGo4',
    appId: '1:90632323398:android:3134a55b85246ce906a547',
    messagingSenderId: '90632323398',
    projectId: 'scorewizard-3d1e9',
    storageBucket: 'scorewizard-3d1e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFEdWps8y8UABSwOzplJqLVVArdi2bz8',
    appId: '1:90632323398:ios:a6533e151302f32b06a547',
    messagingSenderId: '90632323398',
    projectId: 'scorewizard-3d1e9',
    storageBucket: 'scorewizard-3d1e9.appspot.com',
    iosBundleId: 'com.example.scorewizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFEdWps8y8UABSwOzplJqLVVArdi2bz8',
    appId: '1:90632323398:ios:a6533e151302f32b06a547',
    messagingSenderId: '90632323398',
    projectId: 'scorewizard-3d1e9',
    storageBucket: 'scorewizard-3d1e9.appspot.com',
    iosBundleId: 'com.example.scorewizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQnubk7dlL9b4uO9WQ1NyNsslDn9VhfPI',
    appId: '1:90632323398:web:35fb822266957f3106a547',
    messagingSenderId: '90632323398',
    projectId: 'scorewizard-3d1e9',
    authDomain: 'scorewizard-3d1e9.firebaseapp.com',
    storageBucket: 'scorewizard-3d1e9.appspot.com',
  );
}
